# Generated by Django 5.1.5 on 2025-02-17 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoris', '0006_remove_product_image1_remove_product_image2_and_more'),
        ('productdetails', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='variationmanager',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='create',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='varitation',
        ),
        migrations.AddField(
            model_name='variation',
            name='variation',
            field=models.CharField(choices=[('size', 'Size'), ('color', 'Color')], default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='categoris.product'),
        ),
    ]
