# Generated by Django 5.1.5 on 2025-02-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='products/default.jpg', upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='products/default.jpg', upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='products/default.jpg', upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='products/default.jpg', upload_to='products'),
        ),
    ]
