# Generated by Django 5.1.5 on 2025-02-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='Repassword',
            field=models.CharField(max_length=8),
        ),
    ]
